pipeline {
  agent any
  environment {
    PYTHONUNBUFFERED = 'TRUE'
    SAGEMAKER_PROJECT_NAME_ID = """${sh(
      returnStdout: true,
      script: 'echo "${SAGEMAKER_PROJECT_NAME}-${SAGEMAKER_PROJECT_ID}"'
      ).trim()}"""
  }
  stages {
    stage('Build and Install') {
      agent any
      steps {
          withEnv(["HOME=${env.WORKSPACE}"]){
            //sh '''pip3 install --upgrade --force-reinstall --target $HOME/.local/$SAGEMAKER_PROJECT_NAME_ID . "awscli>1.20.30"'''
            // sudo -H pip3 install awscli --upgrade --target $HOME/.local/$SAGEMAKER_PROJECT_NAME_ID --ignore-installed six
            sh '''pip3 install --target $HOME/.local/$SAGEMAKER_PROJECT_NAME_ID awscli --prefer-binary'''
            // python3 setup.py install --exec-prefix='$HOME/.local/$SAGEMAKER_PROJECT_NAME_ID' --prefix='$HOME/.local/$SAGEMAKER_PROJECT_NAME_ID'
            sh '''
            printenv
            echo " Workspace:env:value is  ${WORKSPACE}"
            echo "AWS version is $(aws --version)"
            echo "Env variables are location -- is $HOME/.local/$SAGEMAKER_PROJECT_NAME_ID"
            echo "Env variable HOME is $HOME"
            echo "Env Variable SAGEMAKER_PIPELINE_ROLE_ARN is $SAGEMAKER_PIPELINE_ROLE_ARN"
            echo "Env variable ARTIFACT_BUCKET is $ARTIFACT_BUCKET"
            echo "going to run pip install locally"

            echo "going to run setup.py"
            python setup.py build_scripts
            echo "Going to run a full build now"
            export PYTHONPATH="$HOME/.local/$SAGEMAKER_PROJECT_NAME_ID:$PYTHONPATH"
            export PYTHONPATH="${PYTHONPATH}:$HOME/.local/$SAGEMAKER_PROJECT_NAME_ID/lib/python3.7/site-packages/"
            export PYTHONPATH="${PYTHONPATH}:$HOME/.local/$SAGEMAKER_PROJECT_NAME_ID/lib/python2.7/site-packages/"
            export PYTHONPATH="${PYTHONPATH}:$HOME/.local/$SAGEMAKER_PROJECT_NAME_ID/lib/python3.8/site-packages/"
            export PYTHONPATH="${PYTHONPATH}:$HOME/.local/$SAGEMAKER_PROJECT_NAME_ID/lib/python3.9/site-packages/"
            echo " Finally:after:all:python_path sets pythonpath=$PYTHONPATH "
            echo "Try Pip Install again but in sequence"
            
            pip3 install --upgrade pip setuptools wheel
            pip3 install numpy --upgrade --target $HOME/.local/$SAGEMAKER_PROJECT_NAME_ID
            pip3 install pandas --target $HOME/.local/$SAGEMAKER_PROJECT_NAME_ID
            pip3 install sagemaker --target $HOME/.local/$SAGEMAKER_PROJECT_NAME_ID
            
            #export PATH=/usr/local/anaconda3/bin:$PATH 
            #eval "$(conda shell.bash hook)"
            #conda activate /Users/rsgrewal/Documents/aws/software/conda/sagemaker
            
            python3 setup.py install --prefix='$HOME/.local/$SAGEMAKER_PROJECT_NAME_ID'
            
            echo "All Done  a full INSTALL NOW !!!!"
            '''
          }
      }
    }

    stage('Update and Run Sagemaker Pipeline') {
      agent any
      environment { 
        HOME="${env.WORKSPACE}"
      }
      steps {
          //withCredentials([usernamePassword(credentialsId: 'JENKINS-ACCT3-PASSSTYLE', passwordVariable: 'secretKey', usernameVariable: 'accessKey')]){
          withAWS(credentials: 'AWS_CREDENTIAL', region: 'us-east-1') {

          sh '''export PATH="$HOME/.local/$SAGEMAKER_PROJECT_NAME_ID/bin:$PATH"
          export PYTHONPATH="$HOME/.local/$SAGEMAKER_PROJECT_NAME_ID:$PYTHONPATH"
          export PATH="$HOME/.local/$SAGEMAKER_PROJECT_NAME_ID/bin:$PATH"
          echo "path set up to $PATH "
          
          #export aws_access_key_id=$accessKey
          #export aws_secret_access_key=$secretKey
          #export aws_region=us-east-1
          #aws configure set aws_access_key_id $accessKey
          #aws configure set aws_secret_access_key $secretKey
          #aws configure set default.region us-east-1
          #echo "access key=$accessKey"
          
          echo "Now going to run pipelines"
          echo "now going to run pipelines"
          echo "Before run pipeline::aws_credentials=${AWS-CREDENTIALS}"
          run-pipeline --module-name pipelines.tweets.pipeline \
          --role-arn ${SAGEMAKER_PIPELINE_ROLE_ARN} \
          --tags "[{\\"Key\\":\\"sagemaker:project-name\\", \\"Value\\":\\"${SAGEMAKER_PROJECT_NAME}\\"}, {\\"Key\\":\\"sagemaker:project-id\\", \\"Value\\":\\"${SAGEMAKER_PROJECT_ID}\\"}]" \
          --kwargs "{\\"region\\":\\"${AWS_REGION}\\",\\"sagemaker_project_arn\\":\\"${SAGEMAKER_PROJECT_ARN}\\",\\"role\\":\\"${SAGEMAKER_PIPELINE_ROLE_ARN}\\",\\"default_bucket\\":\\"${ARTIFACT_BUCKET}\\",\\"pipeline_name\\":\\"${SAGEMAKER_PROJECT_NAME_ID}\\",\\"model_package_group_name\\":\\"${SAGEMAKER_PROJECT_NAME_ID}\\",\\"base_job_prefix\\":\\"${SAGEMAKER_PROJECT_NAME_ID}\\"}"'''

          echo "Create/Update of the SageMaker Pipeline and execution completed."
        }
      }
    }

      
      
      
  }
  post {
    always {
      //cleanWs()
      dir("${env.WORKSPACE}@tmp") {
        //deleteDir()
      }
      dir("${env.WORKSPACE}@script") {
        //deleteDir()
      }
      dir("${env.WORKSPACE}@script@tmp") {
        //deleteDir()
      }
   }
  }

}
